packages:
  - examples/*
  - package
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.23.1+sha512-Iv0lXkpG6NXcNu/khNeaNfpcI8KMnyOnmiB+BbwCw1t0csCZPzLf7EJ4zCuvD/yg1oyHquMXzBQHAzyGq+CnZw==
loglevel: info
minimumReleaseAgeExclude:
  - "@oxc-parser/binding-android-arm-eabi@0.140.0"
  - "@oxc-parser/binding-android-arm64@0.140.0"
  - "@oxc-parser/binding-darwin-arm64@0.140.0"
  - "@oxc-parser/binding-darwin-x64@0.140.0"
  - "@oxc-parser/binding-freebsd-x64@0.140.0"
  - "@oxc-parser/binding-linux-arm-gnueabihf@0.140.0"
  - "@oxc-parser/binding-linux-arm-musleabihf@0.140.0"
  - "@oxc-parser/binding-linux-arm64-gnu@0.140.0"
  - "@oxc-parser/binding-linux-arm64-musl@0.140.0"
  - "@oxc-parser/binding-linux-ppc64-gnu@0.140.0"
  - "@oxc-parser/binding-linux-riscv64-gnu@0.140.0"
  - "@oxc-parser/binding-linux-riscv64-musl@0.140.0"
  - "@oxc-parser/binding-linux-s390x-gnu@0.140.0"
  - "@oxc-parser/binding-linux-x64-gnu@0.140.0"
  - "@oxc-parser/binding-linux-x64-musl@0.140.0"
  - "@oxc-parser/binding-openharmony-arm64@0.140.0"
  - "@oxc-parser/binding-wasm32-wasi@0.140.0"
  - "@oxc-parser/binding-win32-arm64-msvc@0.140.0"
  - "@oxc-parser/binding-win32-ia32-msvc@0.140.0"
  - "@oxc-parser/binding-win32-x64-msvc@0.140.0"
  - "@oxc-project/types@0.140.0"
  - oxc-parser@0.140.0
verifyDepsBeforeRun: false
