packages:
  - examples/*
  - package
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.18.0+sha512-jCfqTFQpeocI+kKo3uNkpIEuAthh2zFqNEMQvRNXMmXzyHq/mZ7ou4hGdbLRjcLo4wGPlpRHtufkrCPH2AraNg==
loglevel: info
verifyDepsBeforeRun: false
