packages:
  - examples/*
  - package
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.17.0+sha512-lF6dqB2ELmR0twce/jQJZwcSSjuCTAzz7P+AIQnQFhmPaXeBRkz5cDskGRiqCG9DzEEsgH9NMPJJpvAwaeUqKA==
loglevel: info
verifyDepsBeforeRun: false
