// package/src/descriptors/build.ts
import { Schema } from "effect";
import { Bool, Num, Str, StringArray, StringRecord, UnknownRecord } from "./schemas.js";
import type { FieldDescriptors } from "./types.js";

/** The 26 build / scripts + patches + injection fields. @internal */
export const build = {
	onlyBuiltDependencies: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "warn",
		doc: "Packages whose build scripts are allowed to run; others are blocked.",
		workspaceYaml: true,
		anchor: "onlybuiltdependencies",
	},
	onlyBuiltDependenciesFile: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Path to a JSON file listing packages whose build scripts are allowed.",
		workspaceYaml: true,
		anchor: "onlybuiltdependenciesfile",
	},
	neverBuiltDependencies: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Packages whose build scripts are never executed.",
		workspaceYaml: true,
		anchor: "neverbuiltdependencies",
	},
	ignoredBuiltDependencies: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Packages excluded from the list of dependencies to build.",
		workspaceYaml: true,
		anchor: "ignoredbuiltdependencies",
	},
	dangerouslyAllowAllBuilds: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "warn",
		doc: "When true, all build scripts are allowed to run without restriction.",
		workspaceYaml: true,
		anchor: "dangerouslyallowallbuilds",
	},
	ignoreScripts: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether lifecycle scripts of packages in node_modules are not executed.",
		workspaceYaml: true,
		anchor: "ignorescripts",
	},
	ignoreDepScripts: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether lifecycle scripts of dependencies are ignored during install.",
		workspaceYaml: true,
		anchor: "ignoredepscripts",
	},
	childConcurrency: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Maximum number of child processes that build scripts can spawn concurrently.",
		workspaceYaml: true,
		anchor: "childconcurrency",
	},
	sideEffectsCache: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether the results of running install scripts are cached.",
		workspaceYaml: true,
		anchor: "sideeffectscache",
	},
	sideEffectsCacheReadonly: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether the side effects cache is used but never updated.",
		workspaceYaml: true,
		anchor: "sideeffectscachereadonly",
	},
	nodeOptions: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Options passed to Node.js via NODE_OPTIONS when running scripts.",
		workspaceYaml: true,
		anchor: "nodeoptions",
	},
	verifyDepsBeforeRun: {
		schema: Schema.Union([Schema.Literals(["install", "warn", "error", "prompt"]), Schema.Boolean]),
		kind: "union",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether pnpm verifies that the install is up to date before running scripts.",
		workspaceYaml: true,
		anchor: "verifydepsbeforerun",
		samples: { valid: ["install", false], invalid: ["x"] },
	},
	enablePrePostScripts: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether pre/post lifecycle scripts are run automatically alongside the main script.",
		workspaceYaml: true,
		anchor: "enableprepostscripts",
	},
	scriptShell: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "absent",
		doc: "The shell used to execute scripts.",
		workspaceYaml: true,
		anchor: "scriptshell",
	},
	shellEmulator: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether a POSIX shell emulator is used when running scripts on Windows.",
		workspaceYaml: true,
		anchor: "shellemulator",
	},
	requiredScripts: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Scripts that must exist in every project matching the current filter.",
		workspaceYaml: true,
		anchor: "requiredscripts",
	},
	patchedDependencies: {
		schema: StringRecord,
		kind: "stringRecord",
		strategy: "mapChildWins",
		enforcement: "warn",
		doc: "Patches applied to dependencies, keyed by package identifier.",
		workspaceYaml: true,
		anchor: "patcheddependencies",
	},
	allowUnusedPatches: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether unused patches (patches that apply to no installed package) are allowed.",
		workspaceYaml: true,
		anchor: "allowunusedpatches",
	},
	allowNonAppliedPatches: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether non-applied patches (patches that fail to apply) are allowed.",
		workspaceYaml: true,
		anchor: "allownonappliedpatches",
	},
	ignorePatchFailures: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether patch failures are silently ignored during installation.",
		workspaceYaml: true,
		anchor: "ignorepatchfailures",
	},
	patchesDir: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Directory where patch files are stored (default: patches).",
		workspaceYaml: true,
		anchor: "patchesdir",
	},
	configDependencies: {
		schema: StringRecord,
		kind: "stringRecord",
		strategy: "mapChildWins",
		enforcement: "absent",
		doc: "Packages installed before other packages so their config scripts can run first.",
		workspaceYaml: true,
		anchor: "configdependencies",
	},
	executionEnv: {
		schema: UnknownRecord,
		kind: "unknownRecord",
		strategy: "mapChildWins",
		enforcement: "absent",
		doc: "Environment variables applied when running scripts.",
		workspaceYaml: true,
		anchor: "executionenv",
	},
	injectWorkspacePackages: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether local workspace packages are injected instead of symlinked.",
		workspaceYaml: true,
		anchor: "injectworkspacepackages",
	},
	syncInjectedDepsAfterScripts: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Scripts after which injected dependencies are re-synced.",
		workspaceYaml: true,
		anchor: "syncinjecteddepsafterscripts",
	},
	dedupeInjectedDeps: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether injected workspace packages are deduplicated.",
		workspaceYaml: true,
		anchor: "dedupeinjecteddeps",
	},
} satisfies FieldDescriptors;
