// package/src/descriptors/hoisting.ts
import { Schema } from "effect";
import { Bool, Num, Str, StringArray } from "./schemas.js";
import type { FieldDescriptors } from "./types.js";

/** The 17 hoisting + node-modules + store fields. @internal */
export const hoisting = {
	hoist: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether packages are hoisted to the virtual store root node_modules.",
		workspaceYaml: true,
		anchor: "hoist",
	},
	hoistWorkspacePackages: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether workspace packages are hoisted to the root node_modules.",
		workspaceYaml: true,
		anchor: "hoistworkspacepackages",
	},
	hoistPattern: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Glob patterns describing which packages are hoisted to the virtual store root.",
		workspaceYaml: true,
		anchor: "hoistpattern",
	},
	shamefullyHoist: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether all packages are hoisted to the root node_modules (shameful flat layout).",
		workspaceYaml: true,
		anchor: "shamefullyhoist",
	},
	hoistingLimits: {
		schema: Schema.Literals(["none", "workspaces", "dependencies"]),
		kind: "enum",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Defines the scope to which dependencies are hoisted.",
		workspaceYaml: true,
		anchor: "hoistinglimits",
		samples: { valid: ["none"], invalid: ["x"] },
	},
	modulesDir: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "absent",
		doc: "The directory in which node_modules will be created.",
		workspaceYaml: true,
		anchor: "modulesdir",
	},
	nodeLinker: {
		schema: Schema.Literals(["isolated", "hoisted", "pnp"]),
		kind: "enum",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Defines which linker is used for installing Node.js packages.",
		workspaceYaml: true,
		anchor: "nodelinker",
		samples: { valid: ["isolated"], invalid: ["x"] },
	},
	symlink: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether symlinks are created when linking packages from the store.",
		workspaceYaml: true,
		anchor: "symlink",
	},
	enableModulesDir: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether the local node_modules directory should be created during install.",
		workspaceYaml: true,
		anchor: "enablemodulesdir",
	},
	virtualStoreDir: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "absent",
		doc: "The directory with links to the store (default: node_modules/.pnpm).",
		workspaceYaml: true,
		anchor: "virtualstoredir",
	},
	virtualStoreDirMaxLength: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Maximum allowed length of directory names inside the virtual store.",
		workspaceYaml: true,
		anchor: "virtualstoredirmaxlength",
	},
	virtualStoreOnly: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether packages are written only to the virtual store without a local modules dir.",
		workspaceYaml: true,
		anchor: "virtualstoreonly",
	},
	packageImportMethod: {
		schema: Schema.Literals(["auto", "hardlink", "copy", "clone", "clone-or-copy"]),
		kind: "enum",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Controls how packages are imported from the content-addressable store.",
		workspaceYaml: true,
		anchor: "packageimportmethod",
		samples: { valid: ["auto"], invalid: ["x"] },
	},
	modulesCacheMaxAge: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Maximum age (minutes) of unused modules directories before they are pruned.",
		workspaceYaml: true,
		anchor: "modulescachemaxage",
	},
	dlxCacheMaxAge: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Maximum age (minutes) of cached dlx command results before re-fetch.",
		workspaceYaml: true,
		anchor: "dlxcachemaxage",
	},
	verifyStoreIntegrity: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Whether integrity checksums in the store are verified before using a package.",
		workspaceYaml: true,
		anchor: "verifystoreintegrity",
	},
	strictStorePkgContentCheck: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Whether store package content checksums are verified strictly on each access.",
		workspaceYaml: true,
		anchor: "strictstorepkgcontentcheck",
	},
} satisfies FieldDescriptors;
