// package/src/descriptors/misc.ts
import { Schema } from "effect";
import { Bool, Str } from "./schemas.js";
import type { FieldDescriptors } from "./types.js";

/** The 14 resolution/misc preference fields. @internal */
export const misc = {
	resolutionMode: {
		schema: Schema.Literals(["highest", "time-based", "lowest-direct"]),
		kind: "enum",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Algorithm used to resolve dependencies from the registry.",
		workspaceYaml: true,
		anchor: "resolutionmode",
		samples: { valid: ["highest"], invalid: ["x"] },
	},
	savePrefix: {
		schema: Schema.Literals(["^", "~", ""]),
		kind: "enum",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Version prefix prepended to package versions saved in package.json.",
		workspaceYaml: true,
		anchor: "saveprefix",
		samples: { valid: ["^"], invalid: ["x"] },
	},
	saveExact: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether packages are saved with an exact version instead of a semver range.",
		workspaceYaml: true,
		anchor: "saveexact",
	},
	tag: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "absent",
		doc: "The default tag used when adding packages without a specified version.",
		workspaceYaml: true,
		anchor: "tag",
	},
	preferOffline: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether cached data is used without network requests, failing only if data is missing.",
		workspaceYaml: true,
		anchor: "preferoffline",
	},
	dedupeDirectDeps: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether direct dependencies are deduplicated when they can be satisfied by an existing dependency.",
		workspaceYaml: true,
		anchor: "dedupedirectdeps",
	},
	deployAllFiles: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether all files of a deployed package are copied including those in node_modules.",
		workspaceYaml: true,
		anchor: "deployallfiles",
	},
	forceLegacyDeploy: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether the legacy deployment algorithm (copying files) is used instead of the default.",
		workspaceYaml: true,
		anchor: "forcelegacydeploy",
	},
	extendNodePath: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether the NODE_PATH environment variable is set when running scripts.",
		workspaceYaml: true,
		anchor: "extendnodepath",
	},
	preferSymlinkedExecutables: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether symlinks to executables are created instead of shell shims on non-Windows systems.",
		workspaceYaml: true,
		anchor: "prefersymlinkedexecutables",
	},
	ignoreCompatibilityDb: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether the built-in compatibility database of lifecycle script overrides is ignored.",
		workspaceYaml: true,
		anchor: "ignorecompatibilitydb",
	},
	optimisticRepeatInstall: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether pnpm skips integrity checks when the lockfile is up to date to speed up repeat installs.",
		workspaceYaml: true,
		anchor: "optimisticrepeatinstall",
	},
	recursiveInstall: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether pnpm installs all projects in the workspace when running install in a workspace.",
		workspaceYaml: true,
		anchor: "recursiveinstall",
	},
	engineStrict: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether pnpm fails if a dependency's engines field is incompatible with the current Node.js version.",
		workspaceYaml: true,
		anchor: "enginestrict",
	},
} satisfies FieldDescriptors;
