// package/src/descriptors/network.ts
import { Bool, Num, Str, StringArray } from "./schemas.js";
import type { FieldDescriptors } from "./types.js";

/** The 11 network tuning + publish fields. @internal */
export const network = {
	networkConcurrency: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Maximum number of concurrent network requests pnpm is allowed to make.",
		workspaceYaml: true,
		anchor: "networkconcurrency",
	},
	fetchRetries: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Number of times pnpm retries fetching a package from the registry on failure.",
		workspaceYaml: true,
		anchor: "fetchretries",
	},
	fetchRetryFactor: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Exponential factor used when calculating retry delays for failed fetches.",
		workspaceYaml: true,
		anchor: "fetchretryfactor",
	},
	fetchRetryMintimeout: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Minimum timeout (ms) for a single fetch retry attempt.",
		workspaceYaml: true,
		anchor: "fetchretrymintimeout",
	},
	fetchRetryMaxtimeout: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Maximum timeout (ms) for a single fetch retry attempt.",
		workspaceYaml: true,
		anchor: "fetchretrymaxtimeout",
	},
	fetchTimeout: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Maximum amount of time (ms) to wait for an HTTP response from the registry.",
		workspaceYaml: true,
		anchor: "fetchtimeout",
	},
	gitShallowHosts: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Hosts from which git-protocol dependencies are cloned using a shallow fetch.",
		workspaceYaml: true,
		anchor: "gitshallowhosts",
	},
	provenance: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether packages are published with provenance attestation when supported by the registry.",
		workspaceYaml: true,
		anchor: "provenance",
	},
	gitChecks: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether pnpm checks that the repository is clean before publishing.",
		workspaceYaml: true,
		anchor: "gitchecks",
	},
	embedReadme: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether the README file is embedded in the package tarball on publish.",
		workspaceYaml: true,
		anchor: "embedreadme",
	},
	publishBranch: {
		schema: Str,
		kind: "string",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Branch that is allowed to publish packages; publishing from other branches is blocked.",
		workspaceYaml: true,
		anchor: "publishbranch",
	},
} satisfies FieldDescriptors;
