// package/src/descriptors/resolution.ts
import { Schema } from "effect";
import {
	Bool,
	BooleanRecord,
	Num,
	Str,
	StringArray,
	StringArrayRecord,
	StringRecord,
	UnknownRecord,
} from "./schemas.js";
import type { FieldDescriptors } from "./types.js";

const PeerRulesSchema = Schema.Struct({
	allowedVersions: Schema.optional(StringRecord),
	ignoreMissing: Schema.optional(StringArray),
	allowAny: Schema.optional(StringArray),
});

/**
 * Dependency-resolution category fields. Includes the parity-locked fields
 * migrated from registry.ts + freeze.ts (catalogs, overrides, packageExtensions,
 * allowedDeprecatedVersions, publicHoistPattern, minimumReleaseAgeExclude,
 * supportedArchitectures, auditConfig, peerDependencyRules, strictDepBuilds,
 * blockExoticSubdeps, minimumReleaseAge, allowBuilds, confirmModulesPurge) plus
 * net-new resolution/trust/catalog fields.
 *
 * @internal
 */
export const resolution = {
	catalogs: {
		schema: Schema.Record({ key: Str, value: StringRecord }),
		kind: "object",
		strategy: "catalogs",
		enforcement: "warn",
		doc: "Named version catalogs injected into pnpm config.",
		anchor: "catalogs",
		samples: { valid: [{ default: { lodash: "^4" } }], invalid: ["x"] },
	},
	confirmModulesPurge: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "absent",
		doc: "Whether pnpm prompts before purging node_modules (undocumented upstream).",
	},
	packageExtensions: {
		schema: UnknownRecord,
		kind: "unknownRecord",
		strategy: "mapChildWins",
		enforcement: "absent",
		doc: "Per-package manifest overrides merged into the dependency graph.",
		anchor: "packageextensions",
	},
	allowedDeprecatedVersions: {
		schema: StringRecord,
		kind: "stringRecord",
		strategy: "mapChildWins",
		enforcement: "absent",
		doc: "Deprecated versions explicitly allowed, keyed by package.",
		anchor: "alloweddeprecatedversions",
	},
	publicHoistPattern: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Glob patterns hoisted to the root node_modules.",
		anchor: "publichoistpattern",
		options: { excludeByRepo: true },
	},
	minimumReleaseAgeExclude: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Packages excluded from the minimum-release-age quarantine.",
		anchor: "minimumreleaseageexclude",
	},
	supportedArchitectures: {
		schema: StringArrayRecord,
		kind: "stringArrayRecord",
		strategy: "arrayRecordUnion",
		enforcement: "absent",
		doc: "Supported architectures, keyed by axis (os/cpu/libc).",
		anchor: "supportedarchitectures",
	},
	auditConfig: {
		schema: StringArrayRecord,
		kind: "stringArrayRecord",
		strategy: "arrayRecordUnion",
		enforcement: "absent",
		doc: "Audit config exclusions, keyed by axis.",
		anchor: "auditconfig",
	},
	overrides: {
		schema: StringRecord,
		kind: "stringRecord",
		strategy: "overrides",
		enforcement: "warn",
		doc: "Security version overrides, keyed by package selector.",
		anchor: "overrides",
	},
	peerDependencyRules: {
		schema: PeerRulesSchema,
		kind: "object",
		strategy: "peerDependencyRules",
		enforcement: "warn",
		doc: "Peer dependency rules: allowed versions plus ignore/allow-any lists.",
		anchor: "peerdependencyrules",
		samples: { valid: [{ allowedVersions: { react: "18" } }, {}], invalid: ["x"] },
	},
	strictDepBuilds: {
		schema: Bool,
		kind: "boolean",
		strategy: "securityFlag",
		enforcement: "warn",
		doc: "Whether dependency build scripts are blocked unless explicitly allowed.",
		anchor: "strictdepbuilds",
	},
	blockExoticSubdeps: {
		schema: Bool,
		kind: "boolean",
		strategy: "securityFlag",
		enforcement: "warn",
		doc: "Whether exotic (non-registry) subdependencies are blocked.",
		anchor: "blockexoticsubdeps",
	},
	minimumReleaseAge: {
		schema: Num,
		kind: "number",
		strategy: "securityMin",
		enforcement: "warn",
		doc: "Minimum age (minutes) a release must reach before it is installable.",
		anchor: "minimumreleaseage",
	},
	allowBuilds: {
		schema: BooleanRecord,
		kind: "booleanRecord",
		strategy: "allowBuilds",
		enforcement: "warn",
		doc: "Packages whose build scripts are explicitly allowed to run.",
		anchor: "allowbuilds",
	},
	ignoredOptionalDependencies: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "absent",
		doc: "Optional dependencies excluded from installation entirely.",
		anchor: "ignoredoptionaldependencies",
	},
	updateConfig: {
		schema: Schema.Struct({ ignoreDependencies: Schema.optional(StringArray) }),
		kind: "object",
		strategy: "mapChildWins",
		enforcement: "absent",
		doc: "Per-dependency update behavior: which packages to ignore during updates.",
		anchor: "updateconfig",
		samples: { valid: [{}, { ignoreDependencies: ["a"] }], invalid: ["x"] },
	},
	catalog: {
		schema: StringRecord,
		kind: "stringRecord",
		strategy: "mapChildWins",
		enforcement: "warn",
		doc: "Default version catalog entries merged as a single `default` catalog.",
		anchor: "catalog",
	},
	minimumReleaseAgeStrict: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Whether any resolution fails when a package violates minimum-release-age.",
		anchor: "minimumreleaseagestrict",
	},
	minimumReleaseAgeIgnoreMissingTime: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Whether to skip the release-age check when publish-time metadata is absent.",
		anchor: "minimumreleaseageignoremissingtime",
	},
	trustPolicy: {
		schema: Schema.Literal("off", "no-downgrade"),
		kind: "enum",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Defines what package integrity verification is enforced on installs.",
		anchor: "trustpolicy",
		samples: { valid: ["off"], invalid: ["x"] },
	},
	trustPolicyExclude: {
		schema: StringArray,
		kind: "stringArray",
		strategy: "arrayUnion",
		enforcement: "warn",
		doc: "Packages excluded from trust-policy enforcement.",
		anchor: "trustpolicyexclude",
	},
	trustPolicyIgnoreAfter: {
		schema: Num,
		kind: "number",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Minutes after installation after which the trust check is skipped.",
		anchor: "trustpolicyignoreafter",
	},
	trustLockfile: {
		schema: Bool,
		kind: "boolean",
		strategy: "scalar",
		enforcement: "warn",
		doc: "Whether the lockfile alone is trusted without re-verifying each package's integrity.",
		anchor: "trustlockfile",
	},
} satisfies FieldDescriptors;
